name: CI

on:
  push:
    branches:
      - master

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js
      uses: actions/setup-node@v1
      with:
        version: 12
    - name: Install Dependencies and build into docs Folder
      run:  |
        npm install
        npm run deploy
